<?php

namespace Trinityrank\Multilanguage\Traits;

trait LanguageCode
{

    public static $iso_language_codes = [
        "ae" => "ar-ae", //	Arabic (U.A.E.)
        "af" => "af", //	Afrikaans
        "ar" => "es-ar", //	Spanish (Argentina)
        "at" => "de-at", //	German (Austria)
        "au" => "en-au", //	English (Australia)
        "be" => "nl-be", //	Belgium
        "bg" => "bg", //	Bulgarian
        "bh" => "ar-bh", //	Arabic (Bahrain)
        "bo" => "es-bo", //	Spanish (Bolivia)
        "br" => "pt-br", //	Portuguese (Brazil)
        "bz" => "en-bz", //	English (Belize)
        "ca" => "en-ca", //	Canada
        "ch" => "fr-ch", //	Switzerland
        "cl" => "es-cl", //	Spanish (Chile)
        "cn" => "zh-cn", //	Chinese (PRC)
        "co" => "es-co", //	Spanish (Colombia)
        "cr" => "es-cr", //	Spanish (Costa Rica)
        "cs" => "cs", //	Czech
        "cy" => "cy", //	Welsh
        "da" => "da", //	Danish
        "de" => "de", //	German (Standard)
        "do" => "es-do", //	Spanish (Dominican Republic)
        "dz" => "ar-dz", //	Arabic (Algeria)
        "ec" => "es-ec", //	Spanish (Ecuador)
        "eg" => "ar-eg", //	Arabic (Egypt)
        "el" => "el", //	Greek
        "en" => "en", //	English
        "es" => "es", //	Spanish (Spain)
        "et" => "et", //	Estonian
        "eu" => "eu", //	Basque
        "fa" => "fa", //	Farsi
        "fi" => "fi", //	Finnish
        "fo" => "fo", //	Faeroese
        "fr" => "fr", //	French 
        "ga" => "ga", //	Irish
        "gd" => "gd", //	Gaelic (Scotland)
        "gt" => "es-gt", //	Spanish (Guatemala)
        "he" => "he", //	Hebrew
        "hi" => "hi", //	Hindi
        "hk" => "zh-hk", //	Chinese (Hong Kong)
        "hn" => "es-hn", //	Spanish (Honduras)
        "hu" => "hu", //	Hungarian
        "id" => "id", //	Indonesian
        "ie" => "en-ie", //	English (Ireland)
        "iq" => "ar-iq", //	Arabic (Iraq)
        "is" => "is", //	Icelandic
        "it" => "it", //	Italian (Standard)
        "ja" => "ja", //	Japanese
        "ji" => "ji", //	Yiddish
        "jm" => "en-jm", //	English (Jamaica)
        "jo" => "ar-jo", //	Arabic (Jordan)
        "ko" => "ko", //	Korean
        "ku" => "ku", //	Kurdish
        "kw" => "ar-kw", //	Arabic (Kuwait)
        "lb" => "ar-lb", //	Arabic (Lebanon)
        "li" => "de-li", //	German (Liechtenstein)
        "lt" => "lt", //	Lithuanian
        "lu" => "fr-lu", //	French (Luxembourg)
        "lu" => "de-lu", //	German (Luxembourg)
        "lv" => "lv", //	Latvian
        "ly" => "ar-ly", //	Arabic (Libya)
        "ma" => "ar-ma", //	Arabic (Morocco)
        "md" => "ru-md", //	Russian (Republic of Moldova)
        "mk" => "mk", //	Macedonian (FYROM)
        "ml" => "ml", //	Malayalam
        "ms" => "ms", //	Malaysian
        "mt" => "mt", //	Maltese
        "mx" => "es-mx", //	Spanish (Mexico)
        "nb" => "nb", //	Norwegian (Bokmål)
        "ni" => "es-ni", //	Spanish (Nicaragua)
        "nl" => "nl", //	Dutch (Standard)
        "nn" => "nn", //	Norwegian (Nynorsk)
        "no" => "no", //	Norwegian
        "nz" => "en-nz", //	English (New Zealand)
        "om" => "ar-om", //	Arabic (Oman)
        "pa" => "es-pa", //	Spanish (Panama)
        "pe" => "es-pe", //	Spanish (Peru)
        "pl" => "pl", //	Polish
        "pr" => "es-pr", //	Spanish (Puerto Rico)
        "pt" => "pt", //	Portuguese (Portugal)
        "py" => "es-py", //	Spanish (Paraguay)
        "qa" => "ar-qa", //	Arabic (Qatar)
        "rm" => "rm", //	Rhaeto-Romanic
        "ro" => "ro", //	Romanian
        "ru" => "ru", //	Russian
        "sa" => "ar-sa", //	Arabic (Saudi Arabia)
        "sb" => "sb", //	Sorbian
        "sg" => "zh-sg", //	Chinese (Singapore)
        "sk" => "sk", //	Slovak
        "sl" => "sl", //	Slovenian
        "sq" => "sq", //	Albanian
        "sr" => "sr", //	Serbian
        "sv" => "es-sv", //	Spanish (El Salvador)
        "sv" => "sv", //	Swedish
        "sy" => "ar-sy", //	Arabic (Syria)
        "th" => "th", //	Thai
        "tn" => "ar-tn", //	Arabic (Tunisia)
        "tr" => "tr", //	Turkish
        "ts" => "ts", //	Tsonga
        "tt" => "en-tt", //	English (Trinidad)
        "tw" => "zh-tw", //	Chinese (Taiwan)
        "ua" => "ua", //	Ukrainian
        "uk" => "en-gb", //	English (United Kingdom)
        "ur" => "ur", //	Urdu
        "us" => "en-us", //	English (United States)
        "uy" => "es-uy", //	Spanish (Uruguay)
        "ve" => "es-ve", //	Spanish (Venezuela)
        "ve" => "ve", //	Venda
        "vi" => "vi", //	Vietnamese
        "xh" => "xh", //	Xhosa
        "ye" => "ar-ye", //	Arabic (Yemen)
        "za" => "en-za", //	English (South Africa)
        "zu" => "zu", //	Zulu
    ];
    
    public static $language_names = [
        "ae" => "U.A.E.",
        "af" => "Afrika",
        "ar" => "Argentina",
        "at" => "Austria",
        "au" => "Australia",
        "be" => "Belgium",
        "bg" => "Bulgarian",
        "bh" => "Bahrain",
        "bo" => "Bolivia",
        "br" => "Brazil",
        "bz" => "Belize",
        "ca" => "Canada",
        "ch" => "Switzerland",
        "cl" => "Chile",
        "cn" => "PRC",
        "co" => "Colombia",
        "cr" => "Costa Rica",
        "cs" => "Czech",
        "cy" => "Welsh",
        "da" => "Danish",
        "de" => "German",
        "do" => "Dominican Republic",
        "dz" => "Algeria",
        "ec" => "Ecuador",
        "eg" => "Egypt",
        "el" => "Greek",
        "en" => "English",
        "es" => "Spain",
        "et" => "Estonian",
        "eu" => "Basque",
        "fa" => "Farsi",
        "fi" => "Finland",
        "fo" => "Faeroese",
        "fr" => "France",
        "ga" => "Irish",
        "gd" => "Scotland",
        "gt" => "Guatemala",
        "he" => "Hebrew",
        "hi" => "Hindi",
        "hk" => "Hong Kong",
        "hn" => "Honduras",
        "hu" => "Hungaria",
        "id" => "Indonesia",
        "ie" => "Ireland",
        "iq" => "Iraq",
        "is" => "Icelandic",
        "it" => "Italia",
        "ja" => "Japanese",
        "ji" => "Yiddish",
        "jm" => "Jamaica",
        "jo" => "Jordan",
        "ko" => "Korea",
        "ku" => "Kurdish",
        "kw" => "Kuwait",
        "lb" => "Lebanon",
        "li" => "Liechtenstein",
        "lt" => "Lithuania",
        "lu" => "Luxembourg",
        "lu" => "Luxembourg",
        "lv" => "Latvia",
        "ly" => "Libya",
        "ma" => "Morocco",
        "md" => "Republic of Moldova",
        "mk" => "FYROM",
        "ml" => "Malayalam",
        "ms" => "Malaysia",
        "mt" => "Maltese",
        "mx" => "Mexico",
        "nb" => "Bokmål",
        "ni" => "Nicaragua",
        "nl" => "Nederland",
        "nn" => "Nynorsk",
        "no" => "Norwegian",
        "nz" => "New Zealand",
        "om" => "Oman",
        "pa" => "Panama",
        "pe" => "Peru",
        "pl" => "Polish",
        "pr" => "Puerto Rico",
        "pt" => "Portugal",
        "py" => "Paraguay",
        "qa" => "Qatar",
        "rm" => "Rhaeto-Romanic",
        "ro" => "Romania",
        "ru" => "Russia",
        "sa" => "Saudi Arabia",
        "sb" => "Sorbia",
        "sg" => "Singapore",
        "sk" => "Slovak",
        "sl" => "Slovenia",
        "sq" => "Albania",
        "sr" => "Serbia",
        "sv" => "El Salvador",
        "sv" => "Sweden",
        "sy" => "Syria",
        "th" => "Thai",
        "tn" => "Tunisia",
        "tr" => "Turkish",
        "ts" => "Tsonga",
        "tt" => "Trinidad",
        "tw" => "Taiwan",
        "ua" => "Ukrainia",
        "uk" => "United Kingdom",
        "ur" => "Urdu",
        "us" => "United States",
        "uy" => "Uruguay",
        "ve" => "Venezuela",
        "ve" => "Venda",
        "vi" => "Vietnamese",
        "xh" => "Xhosa",
        "ye" => "Yemen",
        "za" => "South Africa",
        "zu" => "Zulu"
    ];

    public static $badge_language_codes = [
        "ae" => "info", //	Arabic (U.A.E.)
        "af" => "info", //	Afrikaans
        "ar" => "info", //	Spanish (Argentina)
        "at" => "info", //	German (Austria)
        "au" => "info", //	English (Australia)
        "be" => "info", //	Belgium
        "bg" => "info", //	Bulgarian
        "bh" => "info", //	Arabic (Bahrain)
        "bo" => "info", //	Spanish (Bolivia)
        "br" => "info", //	Portuguese (Brazil)
        "bz" => "info", //	English (Belize)
        "ca" => "info", //	Canada
        "ch" => "info", //	Switzerland
        "cl" => "info", //	Spanish (Chile)
        "cn" => "info", //	Chinese (PRC)
        "co" => "info", //	Spanish (Colombia)
        "cr" => "info", //	Spanish (Costa Rica)
        "cs" => "info", //	Czech
        "cy" => "info", //	Welsh
        "da" => "info", //	Danish
        "de" => "info", //	German (Standard)
        "do" => "info", //	Spanish (Dominican Republic)
        "dz" => "info", //	Arabic (Algeria)
        "ec" => "info", //	Spanish (Ecuador)
        "eg" => "info", //	Arabic (Egypt)
        "el" => "info", //	Greek
        "en" => "info", //	English
        "es" => "info", //	Spanish (Spain)
        "et" => "info", //	Estonian
        "eu" => "info", //	Basque
        "fa" => "info", //	Farsi
        "fi" => "info", //	Finnish
        "fo" => "info", //	Faeroese
        "fr" => "info", //	French 
        "ga" => "info", //	Irish
        "gd" => "info", //	Gaelic (Scotland)
        "gt" => "info", //	Spanish (Guatemala)
        "he" => "info", //	Hebrew
        "hi" => "info", //	Hindi
        "hk" => "info", //	Chinese (Hong Kong)
        "hn" => "info", //	Spanish (Honduras)
        "hu" => "info", //	Hungarian
        "id" => "info", //	Indonesian
        "ie" => "info", //	English (Ireland)
        "iq" => "info", //	Arabic (Iraq)
        "is" => "info", //	Icelandic
        "it" => "info", //	Italian (Standard)
        "ja" => "info", //	Japanese
        "ji" => "info", //	Yiddish
        "jm" => "info", //	English (Jamaica)
        "jo" => "info", //	Arabic (Jordan)
        "ko" => "info", //	Korean
        "ku" => "info", //	Kurdish
        "kw" => "info", //	Arabic (Kuwait)
        "lb" => "info", //	Arabic (Lebanon)
        "li" => "info", //	German (Liechtenstein)
        "lt" => "info", //	Lithuanian
        "lu" => "info", //	French (Luxembourg)
        "lu" => "info", //	German (Luxembourg)
        "lv" => "info", //	Latvian
        "ly" => "info", //	Arabic (Libya)
        "ma" => "info", //	Arabic (Morocco)
        "md" => "info", //	Russian (Republic of Moldova)
        "mk" => "info", //	Macedonian (FYROM)
        "ml" => "info", //	Malayalam
        "ms" => "info", //	Malaysian
        "mt" => "info", //	Maltese
        "mx" => "info", //	Spanish (Mexico)
        "nb" => "info", //	Norwegian (Bokmål)
        "ni" => "info", //	Spanish (Nicaragua)
        "nl" => "info", //	Dutch (Standard)
        "nn" => "info", //	Norwegian (Nynorsk)
        "no" => "info", //	Norwegian
        "nz" => "info", //	English (New Zealand)
        "om" => "info", //	Arabic (Oman)
        "pa" => "info", //	Spanish (Panama)
        "pe" => "info", //	Spanish (Peru)
        "pl" => "info", //	Polish
        "pr" => "info", //	Spanish (Puerto Rico)
        "pt" => "info", //	Portuguese (Portugal)
        "py" => "info", //	Spanish (Paraguay)
        "qa" => "info", //	Arabic (Qatar)
        "rm" => "info", //	Rhaeto-Romanic
        "ro" => "info", //	Romanian
        "ru" => "info", //	Russian
        "sa" => "info", //	Arabic (Saudi Arabia)
        "sb" => "info", //	Sorbian
        "sg" => "info", //	Chinese (Singapore)
        "sk" => "info", //	Slovak
        "sl" => "info", //	Slovenian
        "sq" => "info", //	Albanian
        "sr" => "info", //	Serbian
        "sv" => "info", //	Spanish (El Salvador)
        "sv" => "info", //	Swedish
        "sy" => "info", //	Arabic (Syria)
        "th" => "info", //	Thai
        "tn" => "info", //	Arabic (Tunisia)
        "tr" => "info", //	Turkish
        "ts" => "info", //	Tsonga
        "tt" => "info", //	English (Trinidad)
        "tw" => "info", //	Chinese (Taiwan)
        "ua" => "info", //	Ukrainian
        "uk" => "info", //	English (United Kingdom)
        "ur" => "info", //	Urdu
        "us" => "info", //	English (United States)
        "uy" => "info", //	Spanish (Uruguay)
        "ve" => "info", //	Spanish (Venezuela)
        "ve" => "info", //	Venda
        "vi" => "info", //	Vietnamese
        "xh" => "info", //	Xhosa
        "ye" => "info", //	Arabic (Yemen)
        "za" => "info", //	English (South Africa)
        "zu" => "info", //	Zulu
    ];

}